export const INDEX_PAGE = 'INDEX_PAGE';
export const INDEX_PAGE_SUCCESS = 'INDEX_PAGE_SUCCESS';
export const INDEX_PAGE_ERROR = 'INDEX_PAGE_ERROR';
export const ANOTHER_PAGE = 'ANOTHER_PAGE';
export const ANOTHER_PAGE_SUCCESS = 'ANOTHER_PAGE_SUCCESS';
export const ANOTHER_PAGE_ERROR = 'ANOTHER_PAGE_ERROR';